# Generated by Django 5.1.2 on 2024-10-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('publisher', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField()),
                ('style', models.CharField(choices=[('Fiction', 'Ficção'), ('Non-Fiction', 'Não Ficção'), ('Romance', 'Romance'), ('Science', 'Científico'), ('Biography', 'Biografia'), ('Horror', 'Terror')], default='Fiction', max_length=30)),
                ('quantity_total', models.PositiveIntegerField()),
                ('quantity_available', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
