# Generated by Django 5.1.2 on 2024-11-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Active', 'Ativo'), ('Returned', 'Devolvido'), ('Pending', 'Pendente')], default='Active', max_length=20),
        ),
    ]
