# Generated by Django 5.1.2 on 2024-11-04 21:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnloan',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
