# Generated by Django 5.1.2 on 2024-11-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_returnloan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='expected_return_date',
            field=models.DateField(),
        ),
    ]
